### ISSUE TITLE
c14n

### ISSUE THREAD

**Issue by 1602** [libxmljs/libxmljs#127]
Do you plan to provide some c14n methods?

**Comment by bjrmatos** [comment]
If i can collect some money can you guys consider adding c14n support? 

Node.js lacks a robust implementation of xml C14N, so a libxml2 binding will be a huge win, C14N is essentially for xml standars and protocol, like XML Signatures, SAM and many others, since node.js is getting more "enterprise" level these days, this feature is more needed to deal with legacy systems and standards.

I don't have c++ skills to make bindings but i would like to pay some of you to see this in node.js

**Comment by rc0x03** [comment]
You can try using [xml-c14n](https://www.npmjs.com/package/xml-c14n) with `libxmljs-dom`. Just note that libxmljs-dom is still in early development.

**Comment by rc0x03** [comment]
Also, I think it's outside of the scope of this project. It seems like it would be better implemented as a separate project.

**Comment by bjrmatos** [comment]
thnks for the reply @rc0x03 

i know about [xml-c14n](https://www.npmjs.com/package/xml-c14n), in fact xml-c14n was extracted from [xml-crypto](https://github.com/yaronn/xml-crypto), a package where i'm collaborator.

while the c14n implementation in `xml-c14n` and `xml-crypto` has worked very well, it doesn't support plain c14n, only has support for exclusive c14n, it is true that plain c14n can be implemented based in the exclusive c14n implementation in `xml-c14n` or `xml-crypto`.. but you know, the whole xml thing is so legacy that i think nobody wanna mantain a pure js library of xml c14n.. for that reason i think that the most "sane" to do is fall on the shoulders of a robust library like libxml2, write some bindings and let all the implementation details to libxml2.

if i'm not wrong [this is the code in libxml2 with the xml c14n implementation](https://git.gnome.org/browse/libxml2/tree/c14n.c) ([with tests](https://git.gnome.org/browse/libxml2/tree/test/c14n))

i agree that maybe the implementation could be part of another project, something like `xml-c14n-native`, any of you are interested in developing this? if so, i can pay you for your job (i hate myself for not having c++ skills but i guess i must have to learn it in the future..)
