### ISSUE TITLE
cannot extend SaxPushParser

### ISSUE THREAD

**Issue by msklvsk** [libxmljs/libxmljs#349]
Regardless of transpiler the following happens:

``` javascript
import {SaxPushParser} from 'libxmljs';

class SaxPushParserExt extends SaxPushParser {
  on(event, listener) {
    // ...
  }
  foo() {
    // ...
  }
}

let parser = new SaxPushParserExt();

parser.on(/*...*/);  // overload not called, super version called instead
parser.foo();        // TypeError: parser.foo is not a function
```

**Comment by defunctzombie** [comment]
Not sure that the Push parser is really meant to be extended this way. I don't know what specific things are needed to make the `extends` features of es6 work but SaxPushParser is a traditional prototype function/class instance. Happy to review a PR if you find a solution, but I am am unlikely to fix this since I don't use es6 class syntax.

**Comment by rchipka** [comment]
Closing in favor of writing a wrapper class rather than using `extend`
