### ISSUE TITLE
Do consider providing prebuilt binaries

### ISSUE THREAD

**Issue by RobinQu** [libxmljs/libxmljs#395]
Building process of libxml takes too much time, and `npm install` triggers multiple compilation if it's depended by nested packages. 

Maybe it's much more efficient to use prebuilt binaries for some common platforms like darwin and linux64. 

Thanks!

**Comment by rchipka** [comment]
This would also allow users to install libxmljs without having a build environment and help to avoid Visual Studio build environment issues. 

Should it be deployed under separate NPM packages like `libxmljs-win32`, `libxmljs-linux-x86`, `libxml-darwin-x86`, etc? Or should it be deployed using GitHub Releases?

This wouldn't be difficult to accomplished using AppVeyor or [Visual Studio Team Services](https://www.visualstudio.com/en-us/products/visual-studio-team-services-vs.aspx), which both offer GitHub hooks and build deployment. I think AppVeyor would be a better choice since it supports CI and all Node.js versions (VSTS only supports Node 0.12).

@polotek thoughts?

**Comment by hassy** [comment]
Another possible solution is [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp). It's used by several modules, e.g. [node-sqlite3](https://github.com/mapbox/node-sqlite3).

**Comment by rchipka** [comment]
Implemented for Windows. Other platforms tbd.
