### ISSUE TITLE
text() leaks memory

### ISSUE THREAD

**Issue by timdp** [libxmljs/libxmljs#457]
I've noticed that calling `.text()` repeatedly causes the process's RSS (not heap size, as the issue is in native code) to grow.

[Here's a demo.](https://gist.github.com/timdp/036b9631195479c22c2f56f2367f1a73) You'll need to run with `--expose-gc`.

This is with version 0.18.4.

**Comment by zwily** [comment]
Here are my valgrind results from that script. Definitely looks like a leak:

https://gist.github.com/zwily/0ff47925a4f08e9cda11aea4d2a44fab

**Comment by zwily** [comment]
So I know very little about this codebase, but so far have tracked this down to here:

When calling `el.text('string')`, the element contents are replaced here in `set_content`:
 https://github.com/libxmljs/libxmljs/blob/35c4ccffac00d1d0047b1dc768f8036706ef004b/src/xml_element.cc#L436

Which then calls `unlink_children` right above it. In `unlink_children` we iterate over all the children, and unlink them, but never free them. These nodes then leak, because nobody else has a reference to them. I put in a free like so:

```
    xmlUnlinkNode(cur);
    xmlFreeNode(cur);
```

which made the leak go away, but causes this test to segfault: https://github.com/libxmljs/libxmljs/blob/35c4ccffac00d1d0047b1dc768f8036706ef004b/test/ref_integrity.js#L143

It's clear why... We're holding onto an element that got free'd by `unlink_children`. It's not clear to me how ownership is supposed to work here, but this appears to be the root of the problem. I'll keep hacking at it but maybe someone more familiar with the codebase knows an easy fix from here.

**Comment by rchipka** [comment]
We can't `xmlFreeNode` until we're sure that it's no longer referenced in V8, so we must only `xmlUnlinkNode` and `unref_wrapped_ancestor`.

When a [destructor for one of the V8 objects](https://github.com/libxmljs/libxmljs/blob/master/src/xml_node.cc#L440) is called, we can be sure that it's no longer needed and we then `xmlFreeNode` the associated nodes.

The issue here seems to be that we `unlink_children` (which calls `xmlUnlinkNode`) before we call `xmlNodeSetContent`.

Libxml's `xmlNodeSetContent` function already calls `xmlFree` on the old content node, but **only** [if the old content node has an associated document node](https://github.com/GNOME/libxml2/blob/d8083bf77955b7879c1290f0c0a24ab8cc70f7fb/tree.c#L5644)

Because we call `xmlUnlinkNode`, the old content node **cannot** have an associated document node, and therefore will not call `xmlFree`.

**Comment by skif48** [comment]
Hi there!

I'm here to also confirm the memory leak. This caused a lot of problems in our application. Fixed it via using "replace()" kinda like this:
`element.replace(new Element(element.doc(), 'new text')); `

I would like to contribute to the project by solving this issue. Is there anything I can help with?

Thanks.
